import { Dimensions,StyleSheet } from "react-native";

const {width} = Dimensions.get('window');

export const colors = {
    primary: "#5856D6",
    logout:"rgba(211, 9, 9, 0.7)",
    text: "black",
    authBackground: "rgba(28, 103, 216, 0.83)",
    loginBackground: "white",
    protectedBackground:"rgba(231, 239, 241, 0.99)",
    headerBackground: "rgba(27, 152, 201, 0.84)",
    footerBackground: "rgb(27, 152, 201)",
    labelFormText: "rgba(19, 18, 18, 0.75)",
    placeholderText: "rgb(148, 145, 145)",
    cardBackground: "white",
    buttonTextColor: "white",
    headerTextColor: "white",
    footerTextColor: "white",
    alertaTextColor:"rgba(255, 255, 255, 0.97)",
    menuTextOptionsColor:"rgba(255, 255, 255, 0.97)",
    tareaText: "rgba(255, 255, 255, 0.97)",
    errorAlerta: "rgba(201, 11, 11, 0.67)",
    successAlerta: "rgba(23, 153, 204, 0.85)",
    linkText: "rgba(8, 89, 194, 0.74)",
    linkTextHovered:"rgba(207, 7, 67, 0.8)",
    edit:"rgba(73, 170, 89, 0.73)",
    update:"rgba(41, 90, 180, 0.73)",
    delete:"rgba(207, 29, 29, 0.88)",
    menuBackground: "rgba(41, 13, 78, 0.97)",
};

export const globalStyles = StyleSheet.create({

    // Las unidades de los valores numericos estan en pixeles

    titleProtected: {
        fontSize: 30,
        fontWeight: "bold",
        marginBottom: 30,
        color: colors.alertaTextColor,
        textAlign:'center',
    },
    titleLogin:{
        fontSize: 28,
        fontWeight: "bold",
        marginBottom: 35,
        color: colors.text,
        textAlign:'center',
    },
    subTitleProtected:{
        fontSize: 20,
        fontWeight: "bold",
        color: colors.alertaTextColor,
        marginVertical:15, 
    },
    subTitle: {
        fontSize: 20,
        fontWeight: "bold",
        color: colors.text,
        marginVertical:15, 
    },
    tareaText:{
        fontSize: 20,
        fontWeight: "bold",
        width:'35%',
        color: colors.tareaText,
        marginVertical:15, 
    },
    menuTextOptions:{
        fontSize: 17,
        fontWeight: "bold",
        color: colors.menuTextOptionsColor,
        marginVertical: 15, 
        textAlign:'center',
    },
    alertaText:{
        fontSize: width > 474 ? 15 : 10,
        fontWeight: "normal",
        textTransform:'uppercase',
        color: colors.alertaTextColor,
        textAlign:'center', 
    },
    menuContainer:{
        paddingVertical:60,
        paddingHorizontal:30,
        width: width > 474 ? '15%': '100%',
        height: width > 474 ? '100%' : 'auto',
        backgroundColor:colors.menuBackground,
        position: 'absolute',
        zIndex: 6, 
        justifyContent: 'center', // Centrar contenido
        alignItems: 'center', // Centrar contenido
    },
    linkText:{
        fontSize: 15,
        fontWeight: "normal",
        color: colors.linkText,
        marginVertical: 15, 
        textAlign: 'center',
    },
    linkTextProtected:{
        fontSize: 15,
        fontWeight: "normal",
        color: colors.alertaTextColor,
        marginVertical: 15, 
        textAlign: 'center',
    },
    linkTextHovered:{
        fontSize: 15,
        fontWeight: "normal",
        color: colors.linkText,
        marginVertical: 15, 
        textAlign: 'center',
    },
    headerTitleText: {
        fontSize: 30,
        fontWeight: "bold",
        color: colors.headerTextColor,
        textAlign:'center',
    },
    headersubTitleText: {
        fontSize: 20,
        fontWeight: "normal",
        color: colors.headerTextColor,
    },
    footerText: {
        fontSize: 20,
        fontWeight: "bold",
        color: colors.footerTextColor,
    },
    input: {
        height: 40,
        width: 'auto',
        margin: 12,
        borderWidth: 1,
        padding: 10,
        borderColor: 'rgba(0,0,0,0.3)',
        borderRadius: 10,
        backgroundColor:colors.alertaTextColor,
        color: colors.text,
    },
    inputTask:{
        height: 40,
        width: 250,
        margin: 12,
        borderWidth: 1,
        padding: 10,
        borderColor: 'rgba(0,0,0,0.3)',
        borderRadius: 10,
        backgroundColor:colors.alertaTextColor,
        color: colors.text,
    },
    authContainer: {
        flex: 1,
        backgroundColor: colors.authBackground,
    },
    protectedContainer: {
        flex: 1,
        backgroundColor: colors.protectedBackground,
    },
    globalMargin: {
        paddingHorizontal: 20,
        flex: 1,
    },
    btnLogin:{
        backgroundColor: colors.primary,
        borderRadius: 40,
        padding: 20,
        alignItems: "center",
        marginTop: 60,
    },
    btnLogout:{
        backgroundColor: colors.logout,
        borderRadius: 40,
        padding: 20,
        alignItems: "center",
        marginTop: 60,
    },
    btnPrimary:{
        backgroundColor: colors.primary,
        borderRadius: 10,
        padding: 10,
        alignItems: "center",
    },
    btnADD:{
        backgroundColor: colors.primary,
        borderRadius: 2,
        padding: 10,
        flexDirection:'row',
        textAlign:'center',
        width: width > 474 ? 'auto' : '100%',
    },
    btnCloseMenu:{
        backgroundColor: colors.delete,
        borderRadius: 5,
        padding: 3,
        textAlign:'center',
        alignItems: "center",
        marginBottom:100,
    },
    btnPrimaryText: {
        color: colors.text,
        fontSize: 16,
    },
    headerContainer:{
        height: width > 474 ? '10%' : '22%',
        width: '100%',
        backgroundColor: colors.headerBackground,
        flexDirection: width > 474 ? 'row' : 'column',
        justifyContent: width > 474 ? 'space-between' : 'center',
        alignItems: 'center',
        paddingHorizontal:10,
        paddingVertical: width > 474 ? 15 : 2,
        marginTop:0,
        marginBottom:width > 474 ? 30 : 0,
    },
    footerContainer:{
        height: width > 474 ? '10%' : '7%',
        width: '100%',
        backgroundColor: colors.footerBackground,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical:10,
        marginTop: width > 474 ? 30 : 0,
        marginBottom:0,
    },
    errorAlertaContainer:{
        backgroundColor: colors.errorAlerta,
        height: 'auto',
        width: '100%',
        borderRadius:5,
        justifyContent:'center',
        alignItems:'center',
        paddingVertical:10,
        paddingHorizontal: 5,
        marginTop:1,
        marginBottom:10,
    },
    successAlertaContainer:{
        backgroundColor: colors.successAlerta,
        height: 'auto',
        width: '100%',
        borderRadius:5,
        justifyContent:'center',
        alignItems:'center',
        paddingVertical:10,
        paddingHorizontal: 5,
        marginTop:1,
        marginBottom:10,
    },
    loginContainer:{
        marginTop: 180,
        marginBottom: 30,
        paddingHorizontal: width > 474 ? 20 : 25,
        paddingVertical: width > 474 ? 20 : 25,
        marginHorizontal: 'auto',
        backgroundColor: colors.loginBackground,
        width: width > 474 ? '20%' : '60%',
        height: 'auto',
        borderRadius:10,
    },
    registerContainer:{
        marginTop: 60,
        marginBottom: 30,
        paddingHorizontal: width > 474 ? 20 : 25,
        paddingVertical: width > 474 ? 20 : 25,
        marginHorizontal: 'auto',
        backgroundColor: colors.loginBackground,
        width: width > 474 ? '20%' : '60%',
        height: 'auto',
        borderRadius:10,
    },
    labelForm:{
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.labelFormText,
    },
    homeContainer:{
        marginTop:0,
        marginBottom:0,
        marginHorizontal:'auto',
        backgroundColor:colors.authBackground,
        paddingVertical:10,
        paddingHorizontal:5,
        borderRadius: width > 474 ? 20 : 0,
        height: width > 474 ? '75%' : '65%',
        width: width > 474 ? '50%' : '100%',
    },
    addTaskContainer:{
        marginVertical: width > 474 ? 5 : 1,
        flexDirection: width > 474 ? 'row' : 'column' ,
        justifyContent:'center',
        alignItems:'center',
    },
    tareasContainer:{
        marginVertical:2,
    },
    tareaContainer:{
        marginVertical:2,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
    },
    btnContainer:{
        flexDirection:'row',
        marginHorizontal:4,
        justifyContent:'center',
        alignItems:'center',
    },
    btnEditar:{
        backgroundColor: colors.edit,
        borderRadius: 2,
        padding: 8,
        marginHorizontal:10,
        alignItems: 'center',
    },
    btnActualizar:{
        backgroundColor: colors.update,
        borderRadius: 2,
        padding: 8,
        marginHorizontal:10,
        alignItems: "center",
    },
    btnEliminar:{
        backgroundColor: colors.delete,
        borderRadius: 2,
        padding: 8,
        marginHorizontal:1,
        alignItems: "center",
    },
});